name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: EC-FrontEnd
        run: npm install
      - name: Run component tests
        working-directory: EC-FrontEnd
        run: npx cypress run-ct
